### ISSUE TITLE
Swap View: Click to adjust link

### ISSUE THREAD

**Issue by vanaheimex** [vanaheimex/asgard-exchange#121]
Click to adjust should link to the slippage edit page right away, not to the list.

![Screen Shot 2021-03-21 at 10 36 39 PM](https://user-images.githubusercontent.com/76074315/111933479-f3cd2480-8a95-11eb-9f6e-c4d836b17714.png)

**Comment by HooriRn** [comment]
![image](https://user-images.githubusercontent.com/77393482/112529873-69513180-8dc3-11eb-8b1e-e539ddc20bff.png)

fixed in new push also added "saved" breadcrumb.

**Comment by vanaheimex** [comment]
Re-opening this issue. Doesn't link directly to the slippage tolerance anymore.
