### ISSUE TITLE
Upgrading THOR.RUNE bug?

### ISSUE THREAD

**Issue by vanaheimex** [vanaheimex/asgard-exchange#124]
I upgraded my BNB.RUNE by 1 unit to THOR.RUNE once. 

Then I redid it again by 1 BNB.RUNE unit, and now my upgrade list shows this (twice BNB.RUNE):

![Screen Shot 2021-03-21 at 10 47 27 PM](https://user-images.githubusercontent.com/76074315/111934293-81f5da80-8a97-11eb-9baf-6632bccf1cce.png)

**Comment by HooriRn** [comment]
this should be fixed with upgrading balance not pushing to it. but pls check if you can get this bug.
