### ISSUE TITLE
Component: Field (Price / Select): If no arrow = no hover effect

### ISSUE THREAD

**Issue by vanaheimex** [vanaheimex/asgard-exchange#128]
On many views this component goes from a selectable state to an "unselectable state" (i.e. confirmation views, wallet disconnected views, send views etc).

If there is no arrow next to the SELECT / ASSET, then it means it's technically unselectable. That means that it shouldn't have a hover state.

Go over all views and make sure that the hover has been disabled on those instances. It creates less confusion. No hover = can't be selected.

![Screen Shot 2021-03-22 at 2 33 40 AM](https://user-images.githubusercontent.com/76074315/111949626-6b5f7b80-8ab7-11eb-93c7-8eb1722994b0.png)

**Comment by HooriRn** [comment]
Seems ok in upgrade, swap, send pages
