### ISSUE TITLE
Safari/MacOS: Connect Wallet View: the "SELECT" links when hovered should not get a "hand" cursor

### ISSUE THREAD

**Issue by vanaheimex** [vanaheimex/asgard-exchange#148]
When hovering over the "SELECT" links while disconnected, a "hand" cursor shouldn't appear, as it can confuse users that it's a clickable element.

![Screen Shot 2021-03-28 at 7 58 06 PM](https://user-images.githubusercontent.com/76074315/112772659-00a2c880-9000-11eb-9c01-1e039679fe32.png)

**Comment by HooriRn** [comment]
Maybe it was cached on your side, mine is ok.
