### ISSUE TITLE
Upgrading ETH.RUNE to THOR.RUNE: Max tag = Not enough left for gas

### ISSUE THREAD

**Issue by anonfiveone** [vanaheimex/asgard-exchange#16]
When you press "max" tag to upgrade ETH.RUNE to THOR.RUNE, it doesn't leave enough to cover gas fees.

https://user-images.githubusercontent.com/83097467/115942516-a703b180-a478-11eb-9738-8741d8be75d7.mov

**Comment by vanaheimex** [comment]
ETH.ETH (gwei) is the gas fee for upgrade
