### ISSUE TITLE
Received asset goes down because of slippage, as you increase what you want to send?

### ISSUE THREAD

**Issue by vanaheimex** [vanaheimex/asgard-exchange#25]
As you increase the THOR.RUNE you want to send, you receive less and less BNB.USD.

Is this because of slippage?

Just want to make sure it's not a bug.

https://user-images.githubusercontent.com/76074315/111215749-e1408000-85a9-11eb-9c25-dc12f8c97251.mov

**Comment by HooriRn** [comment]
no it is not a bug
