### ISSUE TITLE
Slip Tolerance: Does it prevent you from swapping? Or just a warning?

### ISSUE THREAD

**Issue by vanaheimex** [vanaheimex/asgard-exchange#26]
Does the slip tolerance just give the user a warning, or is it actually used to prevent a swap from occurring? 

If it's designed to prevent a swap from occurring, the button should grey out (if slip is too high), and the error message in the breadcrumb should be:

"SLIP TOLERANCE EXCEEDED" (in red).

What do you think?

![Screen Shot 2021-03-15 at 4 21 13 PM](https://user-images.githubusercontent.com/76074315/111216191-7b082d00-85aa-11eb-9e4e-38890bd6ce96.png)

**Comment by HooriRn** [comment]
I think this is great, it meant to prevent others to do a swap when the swap has higher slippage than your defined one. Which we have now.
