### ISSUE TITLE
Swap/Send/Upgrade/Pool Views: Max tag should never lead to "output amount less than fees".

### ISSUE THREAD

**Issue by anonfiveone** [vanaheimex/asgard-exchange#27]
When you press "max" for a variety of assets, it says "output amount less than fees". Any way it can pre-calculate this so that the value it gives when you press "max" is the true max you can swap or send?

Useful for swap, send, upgrade and pool views.

https://user-images.githubusercontent.com/83097467/116318043-2ac3e380-a782-11eb-9102-d109e995df2b.mov

**Comment by vanaheimex** [comment]
This should be fixed in the new versions of fee estimation.
