### ISSUE TITLE
Wallet View: USD Estimation not working

### ISSUE THREAD

**Issue by vanaheimex** [vanaheimex/asgard-exchange#53]
The estimated USD value of the assets in the wallet doesn't work. Shows "~$ USD" at the moment:

![Screen Shot 2021-03-15 at 6 16 18 PM](https://user-images.githubusercontent.com/76074315/111228408-8ebb8f80-85ba-11eb-9acc-6e8a6ec17162.png)

**Comment by HooriRn** [comment]
- Fixed in previous versions.
