### ISSUE TITLE
Brave/Chrome/macOS: Top Bar: Vertically misaligned + wrong weight

### ISSUE THREAD

**Issue by vanaheimex** [vanaheimex/asgard-exchange#6]
The text in the top bar is vertically misaligned, see this screenshot:

![Screen Shot 2021-03-15 at 1 29 19 PM](https://user-images.githubusercontent.com/76074315/111195271-7768ac00-8592-11eb-9084-d04842c0c5f2.png)

Also update the font weight to: "bolder", or match the exact weight as from the .org website (it seems bolder there).

**Comment by vanaheimex** [comment]
Still vertically uncentered:

![Screen Shot 2021-03-20 at 2 17 36 PM](https://user-images.githubusercontent.com/76074315/111881504-0c9ae480-8987-11eb-851b-2458d094882b.png)

**Comment by HooriRn** [comment]
![image](https://user-images.githubusercontent.com/77393482/112768467-770bee80-9031-11eb-8b9b-05a2849bfcbb.png)

**Comment by vanaheimex** [comment]
On safari + chrome on mac = 

![Screen Shot 2021-03-28 at 7 42 07 PM](https://user-images.githubusercontent.com/76074315/112772239-b3bdf280-8ffd-11eb-9dcf-612a23ced9af.png)
![Screen Shot 2021-03-28 at 7 42 02 PM](https://user-images.githubusercontent.com/76074315/112772240-b3bdf280-8ffd-11eb-87ba-1281c584f393.png)
