### ISSUE TITLE
Wallet disconnection bug

### ISSUE THREAD

**Issue by vanaheimex** [vanaheimex/asgard-exchange#62]
While I was browsing the wallet views, I decided to disconnect from the wallet (using the navigation menu option). It disconnected me, hid the menu.. but I was still able to browse through the wallet as if I was connected.

See this screenshot:

![Screen Shot 2021-03-15 at 7 32 22 PM](https://user-images.githubusercontent.com/76074315/111234568-31790b80-85c5-11eb-820b-77a8740aecea.png)

**Comment by HooriRn** [comment]
- fixed in previous updates
