### ISSUE TITLE
Transactions View: Closing the view doesn't bring you back to SWAP view

### ISSUE THREAD

**Issue by vanaheimex** [vanaheimex/asgard-exchange#78]
When you press the "CLOSE" button on the Transaction View, it doesn't go back to the SWAP view. It just shows an empty page:

https://user-images.githubusercontent.com/76074315/111366821-68edc380-866a-11eb-9deb-a9d463006c02.mov

**Comment by HooriRn** [comment]
for me it seems ok, can you check again please, it might be updated
