### ISSUE TITLE
Component: Button: Swap: Search Asset: Button has the wrong text

### ISSUE THREAD

**Issue by vanaheimex** [vanaheimex/asgard-exchange#84]
On this view the button should say "CANCEL" instead of "CLOSE"

Please make sure that "CANCEL" and "CLOSE" are used properly across the design, as the invasion prototype. They do mean different things :)

![Screen Shot 2021-03-17 at 5 40 42 PM](https://user-images.githubusercontent.com/76074315/111542443-1d114c00-8748-11eb-8358-6890c64b77db.png)

**Comment by HooriRn** [comment]
fixed in a5c2bea933acdb41d56fda83358a0788d5758955 commit
