### ISSUE TITLE
Component: Notice: Font size adjustment based on browser / fit / truncation

### ISSUE THREAD

**Issue by vanaheimex** [vanaheimex/asgard-exchange#95]
In one instance it's very important for the user to see the full address. ASGARDEX's full design was based on making sure that the whole address fits within this notice bar. I believe it assured ~46 characters for the address.

It seems like however different browsers render the font differently, and as a result the address is truncated on some browsers.

Originally it was designed like this: https://mehowbrains685664.invisionapp.com/console/share/7X27Y4UTMB/531639340

On Brave / Chrome, it seems to fit nicely: 

![Screen Shot 2021-03-18 at 5 38 38 PM](https://user-images.githubusercontent.com/76074315/111701157-cae82d80-8810-11eb-8f89-f4f49646067a.png)

But on Safari it seems to truncate it:

![Screen Shot 2021-03-18 at 5 39 10 PM](https://user-images.githubusercontent.com/76074315/111701226-e2bfb180-8810-11eb-8c5d-12fec5f07cac.png)

Can we do the following to solve this issue (no truncating):

For these 2 views exclusively: 

- Asset select view: https://mehowbrains685664.invisionapp.com/console/share/7X27Y4UTMB/531639340
- Asset selected view: https://mehowbrains685664.invisionapp.com/console/share/7X27Y4UTMB/532290870

On Safari, or any browser that truncates the address, lower the font size to 17px instead of 18px.

This would apply to only this one instance for the notice bar. Any other instances it keeps 18px.

**Comment by HooriRn** [comment]
I think we can close this, too.
